version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
    ignore:
      - dependency-name: express
        update-types:
          - version-update:semver-major
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
